### PR TITLE
Adding SolrCloud scripts and configuration files

### LINKED ISSUE #66: added Solr configurations and scripts to the repository
The configuration file(s) and script(s) used to index our CORD database ought to be added to the Reader repository. To do this task "simply" added the configuration(s) to ./etc, and add the script(s) to ./bin

I think the attached files are the ones in question.

[DIHconfigfile.xml.txt](https://github.com/ericleasemorgan/reader/files/4696181/DIHconfigfile.xml.txt)

[solrfields.sh.txt](https://github.com/ericleasemorgan/reader/files/4696183/solrfields.sh.txt)

### PR DESCRIPTION
**Pull request by ralphlevan**

### CODE REVIEW

**Comment by ralphlevan** [comment]
I think I've got all our files and scripts controlled

**Comment by ericleasemorgan** [comment]
Thanks, and I will look at this sooner rather than later, but please understand, I am still learning the in's & out's of GitHub

**Comment by ralphlevan** [comment]
Hmm. It looks like I merged it myself. Sorry! I know it's not important today, but I was hoping to go through the review process, mostly to make sure I hadn't missed something of Art's.

**Comment by ralphlevan** [comment]
Sorry! I don't know what I'm doing either and accidentally committed my
changes to the master branch. It won't cause any problems, but it was rude.
Ralph

**Pull request merged**
