### PR TITLE
Added multiple models to txt2ent.py from scispacy and streamlined pro…

### LINKED ISSUE #70: modify ./bin/txt2ent.py
Please explore and modify ./bin/txt2ent.py  This script takes a file as input and outputs a stream of tab-delimited lines. Each line denotes a file identifier, a sentence identifier, an entity identifier, an entity, and an entity type. See if you can convince spaCy to use a number of different language models so the output of ./bin/txt2ent.py is rich. For example, use an English language model so it output people and organization, but also use a scientific model to it outputs "tissue", "organism", "disease", etc. 'Make sense? @archaeocharlie

### PR DESCRIPTION
**Pull request by archaeocharlie**
This has three scispacy models now in addition to the normal spacy. I changed spacy's model to lg, which has slightly better F1 for NER. Some approaches to cleaning this data need to be explored next.

### CODE REVIEW

**Comment by ericleasemorgan** [comment]
I'm still learning how to use Git; please send me some sample output. --ELM

**Comment by archaeocharlie** [comment]
Here's an example from one file.

Charlie Harper, PhD
*Digital Scholarship Specialist*
*Freedman Center for Digital Scholarship*
*Kelvin Smith Library*
*Case Western Reserve University*
(216)-368-4253 <(216)%20368-4253> | crh92@case.edu

**Comment by ericleasemorgan** [comment]
No file came through. :-(

**Comment by archaeocharlie** [comment]
[output.zip](https://github.com/ericleasemorgan/reader/files/4732233/output.zip)

**Comment by archaeocharlie** [comment]
I guess it doesn't like .tsv!

**Comment by ericleasemorgan** [comment]
'Looks good, and you have already committed. Correct? 

Here are two tweaks. First, at the top of the file, date and sign your good work; add your name to the file. Second, create a configuration at the top the file looking something like this:

  MODELS = ['en_core_web_lg', 'en_ner_craft_md', 'en_ner_jnlpba_md', 'en_ner_bc5cdr_md']

And then lower in the code do:

  for model in MODELS:

This way it easier to see where to add additional models when needed. 

Okay?

**Comment by archaeocharlie** [comment]
Will recommit and do a pull request/merge now!

Charlie Harper, PhD
*Digital Scholarship Specialist*
*Freedman Center for Digital Scholarship*
*Kelvin Smith Library*
*Case Western Reserve University*
(216)-368-4253 <(216)%20368-4253> | crh92@case.edu

**Pull request merged**
