### PR TITLE
Have txt2ent use multiple slurm nodes

### PR DESCRIPTION
**Pull request by dbrower**
This splits the list of files into groups, and has each node work on a single group.

I'm not sure how to test this since it involves slurm, and all the cord paths are hardcoded, so I cannot run it on my own data set.

### CODE REVIEW

**Comment by ericleasemorgan** [comment]
Interesting, very! If you want to give it a go, then I believe you have permissions on the machine to execute `sbatch ./bin/txt2ent-cord.slurm`. Wanna try?

**Comment by dbrower** [comment]
I'll try it out.

**Comment by dbrower** [comment]
I think this is ready to go.  I'm now working on the underlying python script.

**Comment by ericleasemorgan** [comment]
Thanks but I'm still trying to be my brain around it.

**Comment by ericleasemorgan** [comment]
We only have five nodes at our disposal, and as of right now, four of them are in use. When these four nodes die (successfully or unsuccessfully), I will see about merging your pull request and we can give your good work a go. I think we will have to wait about forty-eight hours. Okay?

**Comment by ericleasemorgan** [comment]
Done, but software is never done, and if it were, then it would be called "hardware". Good luck with the use of multiple nodes to do some of our good work. Please share how well it goes.

**Pull request merged**
